import type { ProductTaxonomyContent } from './types'

export const enProductTaxonomy: ProductTaxonomyContent = {
  locale: 'en',
  eyebrow: 'Product Center',
  title: 'Industrial sensing and motion component catalog',
  summary:
    'The bilingual product center is organized around five primary families while preserving deeper industrial sensor taxonomy.',
  description:
    'This stage stabilizes the catalog logic, browsing hierarchy, and inquiry path first. Real models, images, datasheets, and downloads can be attached later without changing the IA.',
  sourceLabel: 'Reference source',
  sourceUrl: 'https://www.hyfcn.com/product.html',
  categoriesTitle: 'Five primary families',
  categoriesSummary:
    'Top-level categories follow Yuelin Technology’s business framing, while industrial sensor subgrouping stays aligned with the reference sensor catalog.',
  industrialSensorsTitle: 'Industrial sensor depth',
  industrialSensorsSummary:
    'This layer keeps the most mature sensor groupings from the reference structure. Phase 03-03 will expand it into subcategory navigation and listing templates.',
  familyCtaLabel: 'Open category',
  consultTitle: 'Need selection support or a project discussion',
  consultBody:
    'If you already know the scenario, equipment structure, or replacement target, start with an inquiry here and refine the exact model or documentation in the next step.',
  consultCtaLabel: 'Request consultation',
  backToCatalogLabel: 'Back to product center',
  relatedFamiliesTitle: 'Related primary families',
  relatedFamiliesSummary:
    'The product center is meant to be browsed as one industrial automation catalog, so adjacent families stay visible instead of disappearing behind isolated detail pages.',
  categoryMetaGroupsLabel: 'Subgroups',
  categoryMetaSeriesLabel: 'Representative series',
  sourceSyncedLabel: 'Reference-aligned',
  projectInferredLabel: 'Project-inferred',
  categories: [
    {
      key: 'industrial-sensors',
      name: 'Industrial sensors',
      summary:
        'Built on the reference sensor structure, covering detection, proximity, recognition, pressure, ultrasonic, magnetic sensing, and accessories.',
      useCase: 'For general sensing, recognition, and status-detection scenarios.',
      source: 'reference-synced',
      groups: [
        {
          slug: 'fiber-sensors',
          name: 'Fiber sensors',
          summary: 'Aligned with the reference groups for fiber amplifiers and fiber units.',
          source: 'reference-synced',
          series: ['Economy digital fiber sensors', 'Dual-display fiber sensors', 'Fiber units'],
        },
        {
          slug: 'photoelectric-sensors',
          name: 'Photoelectric sensors',
          summary: 'Carries the general photoelectric detection structure while laser ranging is elevated to its own top-level family.',
          source: 'reference-synced',
          series: [
            'Compact photoelectric sensors',
            'Rectangular photoelectric sensors',
            'Flat photoelectric sensors',
            'Ultra-thin photoelectric sensors',
            'Mini background suppression sensors',
            'Background suppression sensors',
            'Linear photoelectric sensors',
            'M8 cylindrical photoelectric sensors',
            'M12 cylindrical photoelectric sensors',
            'M18 cylindrical photoelectric sensors',
            'Built-in frame photoelectric sensors',
            'Liquid-level photoelectric sensors',
          ],
        },
        {
          slug: 'displacement-sensors',
          name: 'Displacement measurement sensors',
          summary: 'Keeps the micro and high-precision laser displacement branches.',
          source: 'reference-synced',
          series: ['Micro laser displacement sensors', 'High-precision laser displacement sensors'],
        },
        {
          slug: 'slot-sensors',
          name: 'Slot photoelectric sensors',
          summary: 'Covers connector-based, cable-based, and varying slot-width structures.',
          source: 'reference-synced',
          series: [
            'Connector slot photoelectric sensors',
            'Built-in connector slot photoelectric sensors',
            'Cable slot photoelectric sensors',
            'Small slot photoelectric sensors',
            'Ultra-small slot photoelectric sensors',
            'Wide-slot photoelectric sensors',
          ],
        },
        {
          slug: 'color-and-label-sensors',
          name: 'Color and label sensors',
          summary: 'Groups color recognition and label detection into one browsing lane.',
          source: 'reference-synced',
          series: ['White-light color sensors', 'Digital mark sensors', 'Smart color sensors', 'Label sensors'],
        },
        {
          slug: 'inductive-proximity-sensors',
          name: 'Inductive proximity sensors',
          summary: 'Covers ring, cylindrical, rectangular, and weld-resistant structures.',
          source: 'reference-synced',
          series: [
            'Ring proximity sensors',
            'Economy ring proximity sensors',
            'Tubular proximity sensors',
            'Compact rectangular proximity sensors',
            'Ultra-small cylindrical proximity sensors',
            'Cylindrical proximity sensors',
            'Short-body cylindrical proximity sensors',
            'Rectangular proximity sensors',
            'Weld-resistant inductive proximity sensors',
            'Analog proximity sensors',
          ],
        },
        {
          slug: 'capacitive-proximity-sensors',
          name: 'Capacitive proximity sensors',
          summary: 'Includes liquid-level, corrosion-resistant, and flat capacitive detection branches.',
          source: 'reference-synced',
          series: [
            'Pipe liquid-level proximity sensors',
            'Flat capacitive proximity sensors',
            'Cylindrical capacitive proximity sensors',
            'Corrosion-resistant cylindrical capacitive sensors',
            'Corrosion-resistant liquid-level capacitive sensors',
          ],
        },
        {
          slug: 'industrial-code-readers',
          name: 'Industrial code readers',
          summary: 'Matches the fixed and handheld industrial code-reading equipment structure.',
          source: 'reference-synced',
          series: ['Fixed industrial code readers', 'Handheld industrial code readers'],
        },
        {
          slug: 'vision-sensors',
          name: 'Vision sensors',
          summary: 'Supports image recognition and lightweight visual inspection use cases.',
          source: 'reference-synced',
          series: ['Vision sensors'],
        },
        {
          slug: 'pressure-sensors',
          name: 'Pressure sensors',
          summary: 'Pressure monitoring and corrosion-resistant needs remain as a distinct group.',
          source: 'reference-synced',
          series: ['Dual-display digital pressure sensors', 'Waterproof and corrosion-resistant pressure sensors'],
        },
        {
          slug: 'ultrasonic-sensors',
          name: 'Ultrasonic sensors',
          summary: 'Covers conventional ultrasonic detection and double-sheet inspection.',
          source: 'reference-synced',
          series: ['Cylindrical ultrasonic sensors', 'Ultrasonic single/double-sheet sensors'],
        },
        {
          slug: 'contact-sensors',
          name: 'Contact sensors',
          summary: 'Preserves contact inspection and displacement-contact branches.',
          source: 'reference-synced',
          series: ['Contact sensors', 'Contact displacement sensors'],
        },
        {
          slug: 'magnetic-sensors',
          name: 'Magnetic sensors',
          summary: 'Organized around cylinder magnetic switches and similar magnetic detection scenes.',
          source: 'reference-synced',
          series: ['Cylinder magnetic switches'],
        },
        {
          slug: 'accessories',
          name: 'Accessories',
          summary: 'Starts with cable and connector accessories to keep room for later expansion.',
          source: 'reference-synced',
          series: ['Cable connectors'],
        },
      ],
    },
    {
      key: 'safety-protection-sensors',
      name: 'Safety protection sensors',
      summary:
        'Pulls safety area sensing and safety door locking products into a standalone family for the Yuelin catalog.',
      useCase: 'For line safety, area protection, and interlock scenarios.',
      source: 'reference-synced',
      groups: [
        {
          slug: 'light-curtains-and-area-sensors',
          name: 'Light curtains and area sensors',
          summary: 'Covers base light curtains, ultra-thin curtains, area sensors, and laser scanners.',
          source: 'reference-synced',
          series: ['Base light curtains', 'Ultra-thin light curtains', 'Ultra-thin area sensors', 'Laser scanners'],
        },
        {
          slug: 'safety-door-lock-switches',
          name: 'Safety door lock switches',
          summary: 'Concentrates door locks, door switches, and serialized safety locking devices.',
          source: 'reference-synced',
          series: ['Safety door lock switches', 'Compact safety door switches', 'RDS04 safety door lock series'],
        },
        {
          slug: 'safety-relay-and-non-contact-switches',
          name: 'Safety relays and non-contact switches',
          summary: 'Used for safety relay logic, non-contact safety doors, and magnetic door detection.',
          source: 'reference-synced',
          series: ['Safety relays', 'Non-contact safety door switches', 'Door magnetic switches'],
        },
      ],
    },
    {
      key: 'laser-ranging-sensors',
      name: 'Laser ranging sensors',
      summary:
        'Separates laser ranging, TOF laser sensing, and laser displacement capability into a dedicated laser detection family.',
      useCase: 'For non-contact ranging, laser displacement, and high-precision positioning scenarios.',
      source: 'reference-synced',
      groups: [
        {
          slug: 'laser-ranging',
          name: 'Laser ranging and general laser sensing',
          summary: 'Built around ranging, general laser inspection, and background suppression laser sensing.',
          source: 'reference-synced',
          series: ['Laser ranging sensors', 'Laser sensors', 'Background suppression laser sensors'],
        },
        {
          slug: 'tof-laser-sensors',
          name: 'TOF laser sensors',
          summary: 'Preserves the TOF-oriented laser structure from the reference catalog.',
          source: 'reference-synced',
          series: ['TOF full-metal laser sensors', 'TOF laser sensors'],
        },
        {
          slug: 'laser-displacement',
          name: 'Laser displacement measurement',
          summary: 'Brings micro and high-precision laser displacement into the laser ranging track.',
          source: 'reference-synced',
          series: ['Micro laser displacement sensors', 'High-precision laser displacement sensors'],
        },
      ],
    },
    {
      key: 'linear-guides-and-modules',
      name: 'Linear guides and modules',
      summary:
        'The reference source does not cover linear modules, so this family uses a first-pass structure that can later be replaced with the real catalog.',
      useCase: 'For motion positioning, slide modules, and equipment structure upgrades.',
      source: 'project-inferred',
      groups: [
        {
          slug: 'linear-guides',
          name: 'Linear guides',
          summary: 'Used for baseline guiding, sliding, and precise linear support.',
          source: 'project-inferred',
          series: ['Standard guides', 'Miniature guides', 'Heavy-load guides'],
        },
        {
          slug: 'slide-modules',
          name: 'Slide modules',
          summary: 'Addresses packaged linear units for equipment-side motion requirements.',
          source: 'project-inferred',
          series: ['Single-axis slide modules', 'Compact slide modules', 'High-rigidity slide modules'],
        },
        {
          slug: 'ball-screw-modules',
          name: 'Ball screw modules',
          summary: 'Leans toward higher-precision positioning and repeatability use cases.',
          source: 'project-inferred',
          series: ['Ball screw modules', 'High-precision positioning modules'],
        },
        {
          slug: 'belt-driven-modules',
          name: 'Belt-driven modules',
          summary: 'Fits long-travel, high-tempo, and transfer-oriented linear motion.',
          source: 'project-inferred',
          series: ['High-speed belt modules', 'Long-travel modules'],
        },
        {
          slug: 'positioning-stages',
          name: 'Positioning stages',
          summary: 'Keeps room for future dual-axis or platform-based positioning structures.',
          source: 'project-inferred',
          series: ['Positioning stages', 'Multi-axis combination stages'],
        },
      ],
    },
    {
      key: 'pneumatic-components',
      name: 'Pneumatic components',
      summary:
        'Builds a first-pass pneumatic directory around execution, control, and air preparation so it can later connect with sensing and integration flows.',
      useCase: 'For actuators, valve control, and pneumatic routing scenarios.',
      source: 'project-inferred',
      groups: [
        {
          slug: 'cylinders',
          name: 'Cylinders',
          summary: 'Covers standard, compact, guided, and slim cylinder structures.',
          source: 'project-inferred',
          series: ['Standard cylinders', 'Slim cylinders', 'Guided cylinders'],
        },
        {
          slug: 'solenoid-valves',
          name: 'Solenoid valves',
          summary: 'Core valve components for pneumatic switching and execution control.',
          source: 'project-inferred',
          series: ['5-port 2-position solenoid valves', 'Valve manifolds', 'Manual valves'],
        },
        {
          slug: 'air-preparation',
          name: 'Air preparation units',
          summary: 'Keeps filtration, pressure reduction, and lubrication units in place.',
          source: 'project-inferred',
          series: ['Filter regulators', 'FRL sets', 'Pressure gauges'],
        },
        {
          slug: 'fittings-and-tubing',
          name: 'Fittings and tubing',
          summary: 'Supports pneumatic routing, branching, and installation.',
          source: 'project-inferred',
          series: ['Quick fittings', 'PU tubing', 'Branch connectors'],
        },
        {
          slug: 'vacuum-components',
          name: 'Vacuum components',
          summary: 'Reserves a vacuum branch for pick-and-place and negative-pressure control.',
          source: 'project-inferred',
          series: ['Vacuum generators', 'Suction cups', 'Vacuum filters'],
        },
      ],
    },
  ],
}
