import type { ProductTaxonomyContent } from './types'

export const enProductTaxonomy: ProductTaxonomyContent = {
  locale: 'en',
  eyebrow: 'Taxonomy Preview',
  title: 'Five primary product families with a synced industrial-sensor structure',
  summary:
    'This step turns the five top-level product families and the reference sensor subgroups into one reusable data model for the later product-center pages.',
  sourceLabel: 'Reference aligned with Huayifeng product center',
  sourceUrl: 'https://www.hyfcn.com/product.html',
  categoriesTitle: 'Primary families',
  categoriesSummary:
    'The five top-level families follow your business framing, while the industrial-sensor internals stay aligned with the reference sensor catalog.',
  industrialSensorsTitle: 'Industrial sensor subgroups',
  industrialSensorsSummary:
    'These are the main reference-synced sensor groups that later plans can expand into navigation, listings, and detail-ready templates.',
  categories: [
    {
      key: 'industrial-sensors',
      name: 'Industrial Sensors',
      summary:
        'Built around the reference sensing structure, covering detection, proximity, identification, pressure, ultrasonic, magnetic, and accessory groups.',
      useCase: 'For general sensing, recognition, and status-detection scenarios.',
      source: 'reference-synced',
      groups: [
        {
          slug: 'fiber-sensors',
          name: 'Fiber Sensors',
          summary: 'Matches the reference groups for fiber heads and related amplifiers.',
          source: 'reference-synced',
          series: ['Economy digital fiber sensors', 'Dual-display multifunction fiber sensors', 'Fiber elements'],
        },
        {
          slug: 'photoelectric-sensors',
          name: 'Photoelectric Sensors',
          summary: 'Keeps the main photoelectric detection branches while laser-ranging families stay in their own top-level family.',
          source: 'reference-synced',
          series: [
            'Compact square photoelectric sensors',
            'Square photoelectric sensors',
            'Flat photoelectric sensors',
            'Ultra-thin photoelectric sensors',
            'Miniature background-suppression photoelectric sensors',
            'Background-suppression photoelectric sensors',
            'Linear light background-suppression sensors',
            'M8 cylindrical photoelectric sensors',
            'M12 cylindrical photoelectric sensors',
            'M18 cylindrical photoelectric sensors',
            'Built-in frame photoelectric sensors',
            'Pipe liquid-level photoelectric sensors',
          ],
        },
        {
          slug: 'displacement-sensors',
          name: 'Displacement Measurement Sensors',
          summary: 'Keeps the displacement-measurement branch from the reference page.',
          source: 'reference-synced',
          series: ['Miniature laser displacement sensors', 'High-precision laser displacement sensors'],
        },
        {
          slug: 'slot-sensors',
          name: 'Slot Photoelectric Sensors',
          summary: 'Covers connector, cable, and different slot-width structures.',
          source: 'reference-synced',
          series: [
            'Connector-type slot sensors',
            'Built-in connector slot sensors',
            'Cable-type slot sensors',
            'Compact slot sensors',
            'Ultra-compact slot sensors',
            'Wide-slot sensors',
          ],
        },
        {
          slug: 'color-and-label-sensors',
          name: 'Color and Label Sensors',
          summary: 'Groups color recognition and label detection in one browse layer.',
          source: 'reference-synced',
          series: ['White-light color sensors', 'Digital mark sensors', 'Smart digital color sensors', 'Label sensors'],
        },
        {
          slug: 'inductive-proximity-sensors',
          name: 'Inductive Proximity Sensors',
          summary: 'Includes ring, cylindrical, square, and weld-resistant proximity structures.',
          source: 'reference-synced',
          series: [
            'Ring proximity sensors',
            'Economy ring proximity sensors',
            'Tube-type proximity sensors',
            'Compact square proximity sensors',
            'Ultra-small cylindrical proximity sensors',
            'Cylindrical proximity sensors',
            'Short cylindrical proximity sensors',
            'Square proximity sensors',
            'Weld-spatter resistant inductive proximity sensors',
            'Analog-output cylindrical proximity sensors',
          ],
        },
        {
          slug: 'capacitive-proximity-sensors',
          name: 'Capacitive Proximity Sensors',
          summary: 'Includes liquid-level, corrosion-resistant, and flat capacitive branches.',
          source: 'reference-synced',
          series: [
            'Pipe liquid-level proximity sensors',
            'Flat capacitive proximity sensors',
            'Cylindrical capacitive proximity sensors',
            'Corrosion-resistant cylindrical capacitive proximity sensors',
            'Corrosion-resistant liquid-level capacitive proximity sensors',
          ],
        },
        {
          slug: 'industrial-code-readers',
          name: 'Industrial Code Readers',
          summary: 'Matches the fixed and handheld code-reading devices from the reference page.',
          source: 'reference-synced',
          series: ['Fixed industrial code readers', 'Handheld industrial code readers'],
        },
        {
          slug: 'vision-sensors',
          name: 'Vision Sensors',
          summary: 'Reserved for image recognition and visual inspection style sensing.',
          source: 'reference-synced',
          series: ['Vision sensors'],
        },
        {
          slug: 'pressure-sensors',
          name: 'Pressure Sensors',
          summary: 'Keeps pressure detection and corrosion-resistant use cases as a separate group.',
          source: 'reference-synced',
          series: ['Dual-display digital pressure sensors', 'Waterproof / corrosion-resistant pressure sensors'],
        },
        {
          slug: 'ultrasonic-sensors',
          name: 'Ultrasonic Sensors',
          summary: 'Covers general ultrasonic sensing and double-sheet detection.',
          source: 'reference-synced',
          series: ['Cylindrical ultrasonic sensors', 'Ultrasonic double-sheet detection sensors'],
        },
        {
          slug: 'contact-sensors',
          name: 'Contact Sensors',
          summary: 'Preserves contact detection and contact displacement sensing.',
          source: 'reference-synced',
          series: ['Contact sensors', 'Contact displacement sensors'],
        },
        {
          slug: 'magnetic-sensors',
          name: 'Magnetic Sensors',
          summary: 'Focused on cylinder magnetic switches and similar magnetic detection needs.',
          source: 'reference-synced',
          series: ['Cylinder magnetic switches'],
        },
        {
          slug: 'accessories',
          name: 'Accessories',
          summary: 'Starts with cable-connector style accessories and leaves room to grow.',
          source: 'reference-synced',
          series: ['Cable connectors'],
        },
      ],
    },
    {
      key: 'safety-protection-sensors',
      name: 'Safety Protection Sensors',
      summary:
        'Separates the reference safety/area sensor and safety-door branches into their own primary family for your site IA.',
      useCase: 'For line safety, protected-area detection, and interlock scenarios.',
      source: 'reference-synced',
      groups: [
        {
          slug: 'light-curtains-and-area-sensors',
          name: 'Light Curtains and Area Sensors',
          summary: 'Includes base light curtains, ultra-thin light curtains, area sensors, and lidar scanners.',
          source: 'reference-synced',
          series: ['Basic light curtain sensors', 'Ultra-thin light curtain sensors', 'Ultra-thin area sensors', 'Lidar scanners'],
        },
        {
          slug: 'safety-door-lock-switches',
          name: 'Safety Door Lock Switches',
          summary: 'Covers safety door locks, compact safety door switches, and the SDS04 family.',
          source: 'reference-synced',
          series: ['Safety door lock switches', 'Compact safety door switches', 'SDS04 safety door lock series'],
        },
        {
          slug: 'safety-relay-and-non-contact-switches',
          name: 'Safety Relays and Non-contact Switches',
          summary: 'Keeps relay, non-contact door switch, and magnetic door-switch branches together.',
          source: 'reference-synced',
          series: ['Safety relays', 'Non-contact safety door switches', 'Magnetic door switches'],
        },
      ],
    },
    {
      key: 'laser-ranging-sensors',
      name: 'Laser Ranging Sensors',
      summary:
        'Pulls laser ranging, TOF laser, and laser displacement capabilities out of the reference structure into a dedicated family.',
      useCase: 'For non-contact ranging, laser displacement, and high-precision positioning.',
      source: 'reference-synced',
      groups: [
        {
          slug: 'laser-ranging',
          name: 'Laser Ranging and General Laser Detection',
          summary: 'Built around ranging, general laser sensing, and background-suppression laser products.',
          source: 'reference-synced',
          series: ['Laser ranging sensors', 'Laser sensors', 'Background-suppression laser sensors'],
        },
        {
          slug: 'tof-laser-sensors',
          name: 'TOF Laser Sensors',
          summary: 'Keeps the TOF laser structures from the reference page together.',
          source: 'reference-synced',
          series: ['All-metal TOF laser sensors', 'TOF laser sensors'],
        },
        {
          slug: 'laser-displacement',
          name: 'Laser Displacement Measurement',
          summary: 'Groups miniature and high-precision laser displacement products under the laser-ranging family.',
          source: 'reference-synced',
          series: ['Miniature laser displacement sensors', 'High-precision laser displacement sensors'],
        },
      ],
    },
    {
      key: 'linear-guides-and-modules',
      name: 'Linear Guides and Modules',
      summary:
        'The reference site does not define this family, so this first-pass grouping uses a scalable industrial motion taxonomy that can later be replaced with real catalog data.',
      useCase: 'For motion transfer, positioning modules, and equipment-structure upgrades.',
      source: 'project-inferred',
      groups: [
        {
          slug: 'linear-guides',
          name: 'Linear Guides',
          summary: 'For base guidance, sliding, and precise linear motion support.',
          source: 'project-inferred',
          series: ['Standard guides', 'Miniature guides', 'Heavy-load guides'],
        },
        {
          slug: 'slide-modules',
          name: 'Slide Modules',
          summary: 'For ready-made linear slide units used in equipment-level motion assemblies.',
          source: 'project-inferred',
          series: ['Single-axis slide modules', 'Compact slide modules', 'High-rigidity slide modules'],
        },
        {
          slug: 'ball-screw-modules',
          name: 'Ball Screw Modules',
          summary: 'Suited to positioning use cases where repeatability and precision matter most.',
          source: 'project-inferred',
          series: ['Ball screw modules', 'High-precision positioning modules'],
        },
        {
          slug: 'belt-driven-modules',
          name: 'Belt-driven Modules',
          summary: 'For long-stroke, high-cycle, and transfer-oriented motion needs.',
          source: 'project-inferred',
          series: ['High-speed belt modules', 'Long-stroke modules'],
        },
        {
          slug: 'positioning-stages',
          name: 'Positioning Stages',
          summary: 'Leaves room for future dual-axis or platform-style positioning structures.',
          source: 'project-inferred',
          series: ['Positioning stages', 'Multi-axis platform assemblies'],
        },
      ],
    },
    {
      key: 'pneumatic-components',
      name: 'Pneumatic Components',
      summary:
        'Builds a foundational pneumatic catalog around execution, control, and air-preparation parts so it can later connect cleanly to sensing and integration stories.',
      useCase: 'For execution units, valve control, and air-line connection scenarios.',
      source: 'project-inferred',
      groups: [
        {
          slug: 'cylinders',
          name: 'Cylinders',
          summary: 'Covers standard, compact, guided, and slim cylinder structures.',
          source: 'project-inferred',
          series: ['Standard cylinders', 'Slim cylinders', 'Guided cylinders'],
        },
        {
          slug: 'solenoid-valves',
          name: 'Solenoid Valves',
          summary: 'For air-path switching and execution-layer control.',
          source: 'project-inferred',
          series: ['5-port solenoid valves', 'Valve manifolds', 'Manual valves'],
        },
        {
          slug: 'air-preparation',
          name: 'Air Preparation',
          summary: 'Keeps filtering, pressure control, and lubrication units grouped together.',
          source: 'project-inferred',
          series: ['Filter-regulators', 'FRL units', 'Pressure gauges'],
        },
        {
          slug: 'fittings-and-tubing',
          name: 'Fittings and Tubing',
          summary: 'For pneumatic line connection, branching, and installation.',
          source: 'project-inferred',
          series: ['Push-in fittings', 'PU tubing', 'Air-branch connectors'],
        },
        {
          slug: 'vacuum-components',
          name: 'Vacuum Components',
          summary: 'Reserves space for suction handling and negative-pressure control.',
          source: 'project-inferred',
          series: ['Vacuum generators', 'Suction cups', 'Vacuum filters'],
        },
      ],
    },
  ],
}
