import type { ProductTaxonomyContent } from './types'

export const zhProductTaxonomy: ProductTaxonomyContent = {
  locale: 'zh',
  eyebrow: '产品中心 / Product Center',
  title: '工业传感与执行元件产品目录',
  summary:
    '围绕五大一级类建立双语产品目录，兼顾工业传感器的细分深度与企业站浏览效率。',
  description:
    '当前产品中心先把目录结构、分类逻辑和咨询入口做稳，后续可以继续挂接真实型号、图片、说明书与下载资料。',
  sourceLabel: '参考目录来源',
  sourceUrl: 'https://www.hyfcn.com/product.html',
  categoriesTitle: '五大产品主轴',
  categoriesSummary:
    '一级分类按照跃鳞科技的业务表达来组织，工业传感器内部细分优先对齐参考站的传感产品目录。',
  industrialSensorsTitle: '工业传感器细分',
  industrialSensorsSummary:
    '这一层先承接参考目录里最成熟的传感器分组，后续 03-03 会继续展开子类导航和列表模板。',
  familyCtaLabel: '查看分类',
  consultTitle: '需要选型或项目沟通',
  consultBody:
    '如果你已经有目标场景、设备结构或替换需求，可以先从这里发起咨询，后续再补型号、图纸和更细的技术资料。',
  consultCtaLabel: '发起咨询',
  backToCatalogLabel: '返回产品中心',
  relatedFamiliesTitle: '相关一级分类',
  relatedFamiliesSummary:
    '产品中心不是孤立浏览。你可以顺着同一套工业自动化叙事，继续查看其他一级类和后续解决方案模块。',
  categoryMetaGroupsLabel: '细分类数量',
  categoryMetaSeriesLabel: '代表系列',
  sourceSyncedLabel: '参考站同步',
  projectInferredLabel: '项目推导',
  subgroupCtaLabel: '查看子类',
  subgroupNavigatorTitle: '工业传感器子类导航',
  subgroupNavigatorSummary:
    '以参考目录同步的子类为浏览主轴，再把每个子类展开成可继续接真实目录的列表模板。',
  listingTemplateTitle: '系列列表模板',
  listingTemplateSummary:
    '每个子类页都会先按已知系列建立稳定的目录行结构，后续再往这些行里补型号、图片、参数和下载资料。',
  listingSeriesLabel: '系列',
  listingFocusLabel: '适用重点',
  listingStatusLabel: '当前状态',
  listingReadyLabel: '模板已就绪',
  siblingGroupsTitle: '同级传感器子类',
  siblingGroupsSummary:
    '工业传感器不是单一路径浏览。你可以在同一层里横向切换其他感测子类，再继续深入看具体系列。',
  categories: [
    {
      key: 'industrial-sensors',
      name: '工业传感器',
      summary:
        '以参考站的传感产品结构为底稿，覆盖检测、接近、识别、压力、超声波、磁性与配件等核心分组。',
      useCase: '面向通用感测、识别与状态检测场景。',
      source: 'reference-synced',
      groups: [
        {
          slug: 'fiber-sensors',
          name: '光纤传感器',
          summary: '对应参考目录中的光纤放大器与光纤单元类目。',
          source: 'reference-synced',
          series: ['经济型数字光纤传感器', '双数显光纤传感器', '光纤元件'],
        },
        {
          slug: 'photoelectric-sensors',
          name: '光电传感器',
          summary: '承接通用光电检测结构，激光测距相关能力在一级类中独立展开。',
          source: 'reference-synced',
          series: [
            '小方型光电传感器',
            '方型光电传感器',
            '扁平型光电传感器',
            '超薄型光电传感器',
            '迷你型背景抑制光电传感器',
            '背景抑制光电传感器',
            '线性光电传感器',
            'M8 圆柱型光电传感器',
            'M12 圆柱型光电传感器',
            'M18 圆柱型光电传感器',
            '内置型框型光电传感器',
            '液位光电传感器',
          ],
        },
        {
          slug: 'displacement-sensors',
          name: '位移测量传感器',
          summary: '保留微型与高精度激光位移测量分组。',
          source: 'reference-synced',
          series: ['微型激光位移传感器', '高精度激光位移传感器'],
        },
        {
          slug: 'slot-sensors',
          name: '槽型光电传感器',
          summary: '覆盖连接器型、电缆型以及不同槽宽结构。',
          source: 'reference-synced',
          series: [
            '连接器型槽型光电传感器',
            '内置连接器型槽型光电传感器',
            '电缆型槽型光电传感器',
            '小型槽型光电传感器',
            '超小槽型光电传感器',
            '宽槽型光电传感器',
          ],
        },
        {
          slug: 'color-and-label-sensors',
          name: '颜色与标签传感器',
          summary: '把颜色识别和标签识别放在同一浏览段内。',
          source: 'reference-synced',
          series: ['白光颜色传感器', '数字式色标传感器', '智能型颜色传感器', '标签传感器'],
        },
        {
          slug: 'inductive-proximity-sensors',
          name: '电感式接近传感器',
          summary: '覆盖环形、圆柱型、方型与防焊渣等常见结构。',
          source: 'reference-synced',
          series: [
            '环形接近传感器',
            '经济型环形接近传感器',
            '管型接近传感器',
            '小方型接近传感器',
            '超小圆柱型接近传感器',
            '圆柱型接近传感器',
            '短型圆柱型接近传感器',
            '方型接近传感器',
            '防焊渣电感式接近传感器',
            '模拟量接近传感器',
          ],
        },
        {
          slug: 'capacitive-proximity-sensors',
          name: '电容式接近传感器',
          summary: '包括液位、耐腐蚀与扁平型电容检测分支。',
          source: 'reference-synced',
          series: [
            '管道液位型接近传感器',
            '扁平型电容接近传感器',
            '圆柱型电容接近传感器',
            '耐腐蚀圆柱型电容接近传感器',
            '耐腐蚀液位电容接近传感器',
          ],
        },
        {
          slug: 'industrial-code-readers',
          name: '工业读码器',
          summary: '对应固定式和手持式工业读码设备。',
          source: 'reference-synced',
          series: ['固定式工业读码器', '手持式工业读码器'],
        },
        {
          slug: 'vision-sensors',
          name: '图像识别传感器',
          summary: '承接图像识别与轻量视觉判断场景。',
          source: 'reference-synced',
          series: ['图像识别传感器'],
        },
        {
          slug: 'pressure-sensors',
          name: '压力传感器',
          summary: '压力检测与耐腐蚀需求作为独立组保留。',
          source: 'reference-synced',
          series: ['双数显数字压力传感器', '防水耐腐蚀型压力传感器'],
        },
        {
          slug: 'ultrasonic-sensors',
          name: '超声波传感器',
          summary: '覆盖常规超声波检测与单双张检测。',
          source: 'reference-synced',
          series: ['圆柱型超声波传感器', '超声波单双张检测传感器'],
        },
        {
          slug: 'contact-sensors',
          name: '接触传感器',
          summary: '保留接触式检测与位移检测分支。',
          source: 'reference-synced',
          series: ['接触式传感器', '接触式位移传感器'],
        },
        {
          slug: 'magnetic-sensors',
          name: '磁性传感器',
          summary: '围绕气缸磁性开关一类磁感检测场景。',
          source: 'reference-synced',
          series: ['气缸磁性开关'],
        },
        {
          slug: 'accessories',
          name: '配件',
          summary: '先同步连接器类配件，为后续扩展留口。',
          source: 'reference-synced',
          series: ['电缆连接器'],
        },
      ],
    },
    {
      key: 'safety-protection-sensors',
      name: '安全防护传感器',
      summary:
        '从参考目录中拆出安全区域传感与安全门锁相关产品，独立成跃鳞科技的第二个一级类。',
      useCase: '面向产线安全、区域防护和门禁互锁场景。',
      source: 'reference-synced',
      groups: [
        {
          slug: 'light-curtains-and-area-sensors',
          name: '光幕与区域传感器',
          summary: '覆盖基础型光幕、超薄型光幕、区域传感器与激光雷达扫描仪。',
          source: 'reference-synced',
          series: ['基础型光幕传感器', '超薄型光幕传感器', '超薄型区域传感器', '激光雷达扫描仪'],
        },
        {
          slug: 'safety-door-lock-switches',
          name: '安全门锁开关',
          summary: '集中承接门锁、门开关与系列化安全门锁产品。',
          source: 'reference-synced',
          series: ['安全门锁开关', '小型安全门开关', 'RDS04 系列安全门锁开关'],
        },
        {
          slug: 'safety-relay-and-non-contact-switches',
          name: '安全继电器与非接触开关',
          summary: '用于安全继电、非接触门开关与门磁检测。',
          source: 'reference-synced',
          series: ['安全继电器', '非接触式安全门开关', '门磁开关'],
        },
      ],
    },
    {
      key: 'laser-ranging-sensors',
      name: '激光测距传感器',
      summary:
        '把参考目录中的激光测距、TOF 激光与激光位移测量能力抽出，形成独立的激光检测主轴。',
      useCase: '面向非接触测距、激光位移和高精度定位场景。',
      source: 'reference-synced',
      groups: [
        {
          slug: 'laser-ranging',
          name: '激光测距与通用激光检测',
          summary: '以测距、通用激光检测和背景抑制激光为基础分组。',
          source: 'reference-synced',
          series: ['激光测距传感器', '激光传感器', '背景抑制激光传感器'],
        },
        {
          slug: 'tof-laser-sensors',
          name: 'TOF 激光传感器',
          summary: '保留参考目录中的 TOF 型激光检测结构。',
          source: 'reference-synced',
          series: ['TOF 全金属激光传感器', 'TOF 激光传感器'],
        },
        {
          slug: 'laser-displacement',
          name: '激光位移测量',
          summary: '将微型与高精度激光位移传感器并入激光测距主轴。',
          source: 'reference-synced',
          series: ['微型激光位移传感器', '高精度激光位移传感器'],
        },
      ],
    },
    {
      key: 'linear-guides-and-modules',
      name: '线性滑轨及模组',
      summary:
        '参考目录未覆盖线性模组，这里先按工业传动常见浏览方式建立可扩展分组，后续可替换为真实目录。',
      useCase: '面向传动定位、滑台模组和设备结构升级场景。',
      source: 'project-inferred',
      groups: [
        {
          slug: 'linear-guides',
          name: '线性滑轨',
          summary: '用于基础导向、滑移与精密直线运动支撑。',
          source: 'project-inferred',
          series: ['标准滑轨', '微型滑轨', '重载滑轨'],
        },
        {
          slug: 'slide-modules',
          name: '滑台模组',
          summary: '以现成滑台单元承接设备上的直线运动模组需求。',
          source: 'project-inferred',
          series: ['单轴滑台模组', '紧凑型滑台模组', '高刚性滑台模组'],
        },
        {
          slug: 'ball-screw-modules',
          name: '丝杆模组',
          summary: '偏向高精度定位与重复精度要求较高的场景。',
          source: 'project-inferred',
          series: ['滚珠丝杆模组', '高精度定位模组'],
        },
        {
          slug: 'belt-driven-modules',
          name: '皮带模组',
          summary: '适合长行程、高节拍和搬运类线性运动场景。',
          source: 'project-inferred',
          series: ['高速皮带模组', '长行程模组'],
        },
        {
          slug: 'positioning-stages',
          name: '定位平台',
          summary: '为双轴或平台式定位结构预留后续扩展位。',
          source: 'project-inferred',
          series: ['定位平台', '多轴组合平台'],
        },
      ],
    },
    {
      key: 'pneumatic-components',
      name: '气动元器件',
      summary:
        '围绕执行、控制和气源处理建立基础气动目录分组，作为后续与传感和集成方案联动的底座。',
      useCase: '面向执行机构、阀控与气路连接场景。',
      source: 'project-inferred',
      groups: [
        {
          slug: 'cylinders',
          name: '气缸',
          summary: '涵盖标准、薄型、导杆与紧凑型气缸。',
          source: 'project-inferred',
          series: ['标准气缸', '薄型气缸', '导杆气缸'],
        },
        {
          slug: 'solenoid-valves',
          name: '电磁阀',
          summary: '面向气路切换与执行控制的核心阀类组件。',
          source: 'project-inferred',
          series: ['二位五通电磁阀', '多联阀组', '手动阀'],
        },
        {
          slug: 'air-preparation',
          name: '气源处理',
          summary: '保留过滤、减压和油雾等基础处理单元。',
          source: 'project-inferred',
          series: ['过滤减压阀', '三联件', '压力表'],
        },
        {
          slug: 'fittings-and-tubing',
          name: '接头与管件',
          summary: '用于气路连接、分流和安装。',
          source: 'project-inferred',
          series: ['快速接头', 'PU 管', '分气接头'],
        },
        {
          slug: 'vacuum-components',
          name: '真空元件',
          summary: '为吸附搬运和负压控制场景预留目录。',
          source: 'project-inferred',
          series: ['真空发生器', '吸盘', '真空过滤器'],
        },
      ],
    },
  ],
}
